### ISSUE TITLE
broken histograms after "moved histogram bin options to commons" changes 

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/pixiedust#135]
### Expected behavior
When user selects Histogram, Options dialog appear

### Actual behavior
stacktrace attached
[moved histogram bin options to commons2.txt](https://github.com/ibm-cds-labs/pixiedust/files/784332/moved.histogram.bin.options.to.commons2.txt)

### Steps to reproduce the behavior
Difficult to reproduce this error in first shot but once you circle between other charts and histogram play with binslider a few times

Since i updated source yesterday histogram has been broken. Narrowed it down by commenting out:
#for f in [barChart,lineChart,histogram]:
for f in [barChart,lineChart]:

binslider is turned off because of commenting out.

Not sure what's the root cause for:

\n/Users/chetnadwarade/pixiedust/pixiedust/display/chart/renderers/baseChartDisplay.pyc in wrapper(cls, *args, **kwargs)
     94             if callable(handler):
     95                 handler = handler(cls)
---> 96             commonOptions += handler
     97             fctSet = set()
     98             for cl in reversed(inspect.getmro(cls.__class__)):
\nTypeError: 'NoneType' object is not iterable\n

**Comment by chetnawarade** [comment]
original stacktrace
[moved histogram bin options to commons1.txt](https://github.com/ibm-cds-labs/pixiedust/files/784365/moved.histogram.bin.options.to.commons1.txt)

**Comment by chetnawarade** [comment]
calculating bin size is flawed that results in:

2017-02-17 16:28:26,342 - pixiedust.display.chart.renderers.baseChartDisplay.BaseChartDisplay - ERROR - Unexpected error while trying to render BaseChartDisplay
Traceback (most recent call last):
  File "/Users/chetnadwarade/pixiedust/pixiedust/display/chart/renderers/baseChartDisplay.py", line 350, in doRender
    chartFigure = self.doRenderChart()
  File "/Users/chetnadwarade/pixiedust/pixiedust/display/chart/renderers/bokeh/bokehBaseDisplay.py", line 58, in doRenderChart
    charts = self.createBokehChart()
  File "/Users/chetnadwarade/pixiedust/pixiedust/display/chart/renderers/bokeh/histogramDisplay.py", line 83, in createBokehChart
    xgrid=True, ygrid=True)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/builders/histogram_builder.py", line 106, in Histogram
    return create_and_build(HistogramBuilder, data, **kw)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/builder.py", line 73, in create_and_build
    chart.add_builder(builder)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/chart.py", line 170, in add_builder
    builder.create(self)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/builder.py", line 537, in create
    chart.add_renderers(self, renderers)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/chart.py", line 165, in add_renderers
    self.renderers += renderers
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/core/property_containers.py", line 18, in wrapper
    result = func(*args, **kwargs)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/core/property_containers.py", line 77, in __iadd__
    return super(PropertyValueList, self).__iadd__(y)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/builders/bar_builder.py", line 220, in yield_renderers
    **group_kwargs)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 949, in __init__
    super(HistogramGlyph, self).__init__(**kwargs)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 489, in __init__
    super(AggregateGlyph, self).__init__(**kwargs)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/models.py", line 81, in __init__
    self.setup()
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/models.py", line 85, in setup
    self.renderers = [renderer for renderer in self.build_renderers()]
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/glyphs.py", line 965, in build_renderers
    density=self.density)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/stats.py", line 311, in __init__
    super(BinnedStat, self).__init__(**properties)
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/stats.py", line 56, in __init__
    self._refresh()
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/stats.py", line 62, in _refresh
    self.calculate()
  File "/Users/chetnadwarade/anaconda/lib/python2.7/site-packages/bokeh/charts/stats.py", line 431, in calculate
    self.bin_width = np.round(bin_bounds[2] - bin_bounds[1], 1)
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by vabarbosa** [comment]
bokeh is failign with binsize less than 2
changed default binsize (min=2, default=3, max=3)
see https://github.com/ibm-cds-labs/pixiedust/commit/8c56a9e4ecbac9cee9688b8fda003999e7337f99

**Comment by vabarbosa** [comment]
@chetnawarade please review if issue has been resolved. thx

**Comment by chetnawarade** [comment]
> To construct a histogram, the first step is to "bin" the range of values—that is, divide the entire range of values into a series of intervals—and then count how many values fall into each interval. The bins are usually specified as consecutive, non-overlapping intervals of a variable.
Histogram - Wikipedia
https://en.wikipedia.org/wiki/Histogram

In the current implementation of the slider, bin is a range computed likely from the #(count) of rows. From the definition ^ a min and max range needs to be computed from the values instead. 

In the home sales data e.g. if plotting histogram of YEAR BUILT bin range from 4-48 is computed 
which happens to work out okay because there are 125 distinct year types in the data and the intervals displayed are close to # of homes/year. This is not easy for the user figure to out at a quick glance.

`df.select("YEAR BUILT").distinct().count()`
`125`

If plotting histogram of PRICE, however an interval of $10,000 to $50,000 will show correct distribution of the PRICE/YEAR over the period of last 300 years. This complexity is due to the nature of the data rather than implementation itself.

I propose we either implement computing max and min of values of each key or give a text box for the user to alter min and max values for the slider, pass it to the api. I love slider to check how the distribution varies with the bin size.

@vabarbosa  @DTAIEB moving to 1.1.

**Comment by DTAIEB** [comment]
@chetnawarade Histogram plot the frequency distribution for each intervals. Calculating reasonable ranges has nothing to do with the actual range of the values. For example: I could have 10 millions data points and be only interested into 2 bins (lower half and upper half). for this example, the most I can "bin" is 10 Millions. So I think the way @vabarbosa implemented it is correct.
Closing this issue for now, feel free to reopen for 1.1 if you disagree.
