### ISSUE TITLE
display() scatterplot

### ISSUE THREAD

**Issue by rajrsingh** [ibm-cds-labs/pixiedust#215]
As a `<user type>`, I want to `<task>` so that `<goal>` (make this the title)

### Expected behavior
scatterplot with renderer menu on right side

### Actual behavior
some red error message flashes briefly, then 
scatterplot is shown, but no renderer menu on right side
also Options button is not displayed

### Steps to reproduce the behavior
1. use million dollar home sample data
2. use PRICE and DAYS ON MARKET as key and value

**Comment by rajrsingh** [comment]
debug log:
```
2017-03-01 12:54:29,372 - pixiedust.display.display.Display - DEBUG - Value Fields: ['PRICE', 'BEDS', 'BATHS', 'YEAR BUILT', 'DAYS ON MARKET', 'LISTING ID']
2017-03-01 12:54:29,372 - pixiedust.utils.template - DEBUG - Template already qualified pixiedust.display.chart.renderers.baseChartDisplay:baseChartOptionsDialogBody.html
2017-03-01 12:54:29,388 - pixiedust.display.display.Display - ERROR - Unexpected error while trying to render BaseChartDisplay
Traceback (most recent call last):
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/baseChartDisplay.py", line 342, in doRender
    raise Exception(errorMessage)
Exception: Can only specify one Value Field
2017-03-01 12:54:51,146 - pixiedust.display - DEBUG - Creating a new display handler with options {'nostore_bokeh': 'false', 'kind': 'simple', 'cell_id': '5CCC869E9980477680A50EE717326C4B', 'prefix': 'e6ab8e91', 'showLegend': 'true', 'aggregation': 'SUM', 'rowCount': '100', 'handlerId': 'scatterPlot', 'valueFields': 'DAYS ON MARKET', 'keyFields': 'PRICE', 'debug': 'true', 'nostore_pixiedust': 'false', 'mapboxtoken': 'pk.eyJ1IjoicmFqcnNpbmdoIiwiYSI6ImpzeDhXbk0ifQ.VeSXCxcobmgfLgJAnsK3nw', 'nostore_cw': '1098'}: <pixiedust.display.chart.ChartDisplayMeta object at 0x11a55f350>
2017-03-01 12:54:51,146 - pixiedust.display.chart.renderers - DEBUG - Found renderer: seaborn - scatterPlot
2017-03-01 12:54:51,146 - pixiedust.display.display.Display - DEBUG - Key Fields: ['PRICE']
2017-03-01 12:54:51,147 - pixiedust.display.chart.renderers.baseChartDisplay - DEBUG - Found cache data for 5CCC869E9980477680A50EE717326C4B. Validating integrity...
2017-03-01 12:54:51,147 - pixiedust.display.chart.renderers.baseChartDisplay - DEBUG - Cache data not validated for key xFields. Expected Value is ['LATITUDE', 'LONGITUDE']. Got ['PRICE']. Destroying it!...
2017-03-01 12:54:51,310 - pixiedust.display.display.Display - DEBUG - getWorkingPandasDataFrame returns:        PRICE  DAYS ON MARKET
24   1000000              87
79   1010000              59
75   1010000              43
71   1037000              49
84   1042500              42
48   1047500              29
54   1060000              21
86   1070000              50
10   1070000              71
25   1075000              86
30   1080000              84
9    1082500              74
46   1100000              30
53   1117500              45
19   1131250              78
32   1132500              29
101  1137000              15
93   1147900              59
50   1150000               1
13   1150000              78
42   1175000              30
38   1175000               4
78   1179000              56
45   1180000              38
96   1185000              23
83   1200000              42
29   1215000              84
97   1230000              88
89   1235000              52
65   1250000              52
..       ...             ...
43   1705000              58
4    1725000              59
57   1745000              22
23   1750000              60
81   1789000              49
33   1800000              36
87   1840000              57
64   1900000              43
66   1950000              50
98   1985000              85
85   1995000              49
3    2038888              58
99   2075000              81
95   2155000              45
56   2185000              23
6    2225000              58
5    2375000              67
37   2425000              15
0    2450000              84
94   2475000              36
61   2530000              39
58   2700000              35
22   2950000              84
2    3100000              58
77   3225000              43
88   3750000              57
11   3780000              81
59   4500000              42
69   4850000              58
1    8950000              86

[102 rows x 2 columns]
2017-03-01 12:54:51,310 - pixiedust.display.display.Display - DEBUG - Key Fields Labels: [1600000, 1685000, 1450000, 1215000, 1300000, 1550000, 1705000, 1457500, 1150000, 1235000, 1320000, 1180000, 1042500, 1725000, 2450000, 1575000, 1399900, 2038888, 3750000, 1425000, 1275000, 1360000, 1528000, 1082500, 1060000, 1350000, 2425000, 1230000, 1080000, 4500000, 1037000, 2530000, 1179000, 1789000, 2700000, 1250000, 1185000, 8950000, 1131250, 1995000, 1520000, 1269000, 4850000, 1800000, 1460000, 1950000, 2185000, 1630000, 1605000, 1454900, 1075000, 1745000, 1117500, 1480000, 1100000, 1437000, 1010000, 1555000, 2375000, 1137000, 1500000, 1649000, 1400000, 2950000, 2075000, 1200000, 1288000, 1349000, 1370000, 2225000, 1000000, 3780000, 1840000, 3225000, 1070000, 3100000, 1560000, 1599938, 1554375, 1047500, 1512400, 2475000, 1533000, 1132500, 1175000, 1900000, 1650000, 1985000, 1750000, 2155000, 1147900]
2017-03-01 12:54:51,310 - pixiedust.display.display.Display - DEBUG - Value Fields: ['DAYS ON MARKET']
2017-03-01 12:54:51,310 - pixiedust.utils.template - DEBUG - Template already qualified pixiedust.display.chart.renderers.baseChartDisplay:baseChartOptionsDialogBody.html
2017-03-01 12:54:51,587 - pixiedust.display.display.Display - ERROR - Unexpected error while trying to render BaseChartDisplay
Traceback (most recent call last):
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/baseChartDisplay.py", line 353, in doRender
    chartFigure = self.doRenderChart()
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/matplotlib/matplotlibBaseDisplay.py", line 143, in doRenderChart
    fig, ax = self.createFigure()
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/seaborn/scatterPlotDisplay.py", line 47, in createFigure
    facetGrid = sns.jointplot(x=keyFields[0], y=valueFields[0], kind=self.options.get("kind","scatter"), data=self.getWorkingPandasDataFrame())
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/seaborn/distributions.py", line 857, in jointplot
    raise ValueError(msg)
ValueError: kind must be either 'scatter', 'reg', 'resid', 'kde', or 'hex'
2017-03-01 12:55:16,440 - pixiedust.display - DEBUG - Creating a new display handler with options {'debug': 'true'}: <pixiedust.display.display.CellHandshakeMeta object at 0x11d5be4d0>
2017-03-01 12:55:16,991 - pixiedust.display - DEBUG - Creating a new display handler with options {'debug': 'true', 'cell_id': '32FE7F85180740108F57C54BFD3ECAE4', 'nostore_bokeh': 'false', 'nostore_pixiedust': 'false', 'nostore_cw': '1098'}: <pixiedust.display.table.TableDisplayMeta object at 0x11a55ff10>
2017-03-01 12:55:17,414 - pixiedust.display - DEBUG - Creating a new display handler with options {'cell_id': '32FE7F85180740108F57C54BFD3ECAE4', 'prefix': '3f66f75e', 'nostore_cw': '1098', 'handlerId': 'dataframe', 'debug': 'true', 'nostore_bokeh': 'false', 'nostore_pixiedust': 'false'}: <pixiedust.display.table.TableDisplayMeta object at 0x11a55ff10>
2017-03-01 12:55:24,896 - pixiedust.display - DEBUG - Creating a new display handler with options {'cell_id': '32FE7F85180740108F57C54BFD3ECAE4', 'prefix': '3f66f75e', 'nostore_cw': '1098', 'handlerId': 'scatterPlot', 'debug': 'true', 'nostore_bokeh': 'false', 'nostore_pixiedust': 'false'}: <pixiedust.display.chart.ChartDisplayMeta object at 0x11a55f350>
2017-03-01 12:55:24,896 - pixiedust.display.chart.renderers - DEBUG - Found renderer: seaborn - scatterPlot
2017-03-01 12:55:24,897 - pixiedust.utils.template - DEBUG - Template already qualified pixiedust.display.chart.renderers.baseChartDisplay:baseChartOptionsDialogBody.html
2017-03-01 12:55:31,106 - pixiedust.display - DEBUG - Creating a new display handler with options {'cell_id': '32FE7F85180740108F57C54BFD3ECAE4', 'prefix': '3f66f75e', 'nostore_cw': '1098', 'rowCount': '100', 'handlerId': 'scatterPlot', 'valueFields': 'DAYS ON MARKET', 'keyFields': 'PRICE', 'debug': 'true', 'nostore_bokeh': 'false', 'nostore_pixiedust': 'false'}: <pixiedust.display.chart.ChartDisplayMeta object at 0x11a55f350>
2017-03-01 12:55:31,106 - pixiedust.display.chart.renderers - DEBUG - Found renderer: seaborn - scatterPlot
2017-03-01 12:55:31,107 - pixiedust.display.display.Display - DEBUG - Key Fields: ['PRICE']
2017-03-01 12:55:31,107 - pixiedust.display.chart.renderers.baseChartDisplay - DEBUG - No Cache Entry found for 32FE7F85180740108F57C54BFD3ECAE4
2017-03-01 12:55:31,218 - pixiedust.display.display.Display - DEBUG - getWorkingPandasDataFrame returns:         PRICE  DAYS ON MARKET
38    1000000              38
60    1000000              43
47    1010000              14
92    1010000              59
55    1020000              37
30    1025000              57
46    1025000              17
89    1025000              53
71    1025500              51
73    1025900              49
105   1045000              88
54    1049000              44
76    1049000              43
17    1049900              87
53    1050000              53
32    1050000              21
15    1050000              87
57    1060000              21
97    1070000              50
18    1075000              86
67    1080000              49
99    1082250              49
4     1082500              74
3     1100000              66
106   1100000              60
33    1100000              39
74    1105000              59
103   1126600              45
11    1131250              78
24    1132500              29
..        ...             ...
87    1650000              49
86    1650000              43
81    1650000              43
65    1663000              57
37    1685000              43
98    1685000              43
44    1695000              31
93    1789000              49
52    1825000              46
25    1899000              22
70    1900000              43
9     1935000              80
80    1950000              53
75    1950000              50
41    1950000              18
96    1995000              49
28    2100000               7
79    2162500              49
0     2165000              88
10    2250000              78
26    2291250               9
95    2320500              73
6     2330000              78
27    2425000              15
68    2430000              58
2     2500000              59
62    2900000              50
16    2950000              84
21    3850000              84
36   10900000              45

[110 rows x 2 columns]
2017-03-01 12:55:31,218 - pixiedust.display.display.Display - DEBUG - Key Fields Labels: [1600000, 1045000, 1450000, 1663000, 10900000, 1150000, 1685000, 2291250, 1235000, 1277500, 1000000, 2430000, 1789000, 1020000, 2250000, 1105000, 2320500, 1275000, 1360000, 1400000, 1082500, 1210000, 1935000, 1337500, 1060000, 1350000, 2425000, 1230000, 1080000, 1300000, 1126600, 1141450, 1650000, 1100000, 1825000, 1590000, 1131250, 1995000, 1520000, 2165000, 3850000, 1695000, 2100000, 1950000, 1049900, 1630000, 1285000, 1075000, 1480000, 2162500, 1010000, 1555000, 2330000, 1457500, 1290000, 1499999, 1180000, 1530000, 1137000, 1025900, 2950000, 1025000, 1179000, 1200000, 1288000, 1349000, 1082250, 1050000, 2500000, 1262500, 1049000, 1070000, 1475000, 1299900, 1240000, 1599938, 2900000, 1325000, 1132500, 1175000, 1025500, 1900000, 1330000, 1345000, 1899000, 1460000]
2017-03-01 12:55:31,219 - pixiedust.display.display.Display - DEBUG - Value Fields: ['DAYS ON MARKET']
2017-03-01 12:55:31,219 - pixiedust.utils.template - DEBUG - Template already qualified pixiedust.display.chart.renderers.baseChartDisplay:baseChartOptionsDialogBody.html
2017-03-01 12:55:31,411 - pixiedust.display.display.Display - ERROR - Unexpected error while trying to render BaseChartDisplay
Traceback (most recent call last):
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/baseChartDisplay.py", line 353, in doRender
    chartFigure = self.doRenderChart()
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/matplotlib/matplotlibBaseDisplay.py", line 143, in doRenderChart
    fig, ax = self.createFigure()
  File "/Users/rajrsingh/workspace/lib/pixiedust/pixiedust/display/chart/renderers/seaborn/scatterPlotDisplay.py", line 47, in createFigure
    facetGrid = sns.jointplot(x=keyFields[0], y=valueFields[0], kind=self.options.get("kind","scatter"), data=self.getWorkingPandasDataFrame())
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/seaborn/distributions.py", line 805, in jointplot
    grid.plot_marginals(distplot, **marginal_kws)
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/seaborn/axisgrid.py", line 1730, in plot_marginals
    func(self.x, **kwargs)
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/seaborn/distributions.py", line 212, in distplot
    color=hist_color, **hist_kws)
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 6010, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/Users/rajrsingh/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 728, in histogram
    n = np.zeros(bins, ntype)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

**Comment by rajrsingh** [comment]
upgrading seaborn from 0.6 to 0.7.1 fixed it
