### ISSUE TITLE
Cannot download data to file on notebook running Python 3.5

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/pixiedust#297]
As a user, I want to download my data to a file

### Expected behavior

Able to download data to CSV, XML, JSON, HTML, or Markdown.

### Actual behavior

Unable to download (Plain Text does work). No error message displayed. Output from pixiedust log:

```
2017-04-06 13:21:26,824 - pixiedust.display - DEBUG - Creating a new display handler with options {'aggregation': 'SUM', 'nostore_cw': '1514', 'nostore_pixiedust': 'false', 'prefix': 'a31238c7', 'rowCount': '100', 'nostore_bokeh': 'false', 'cell_id': '9EADEDD2E8F941C882A4B199F30E2912', 'handlerId': 'downloadFile', 'doDownloadCount': 2, 'keyFields': 'Colors', 'title': 'Colors in this pie chart, by %', 'doDownload': 'csv', 'valueFields': '%'}: <pixiedust.display.download.DownloadMeta object at 0x7f866b7c24e0>
2017-04-06 13:21:26,967 - pixiedust.display - DEBUG - Creating a new display handler with options {'aggregation': 'SUM', 'nostore_cw': '1514', 'nostore_pixiedust': 'false', 'prefix': 'a31238c7', 'doDownloadLink': 'True', 'rowCount': '100', 'nostore_bokeh': 'false', 'cell_id': '9EADEDD2E8F941C882A4B199F30E2912', 'handlerId': 'downloadFile', 'doDownloadCount': 2, 'keyFields': 'Colors', 'title': 'Colors in this pie chart, by %', 'doDownload': 'csv', 'valueFields': '%'}: <pixiedust.display.download.DownloadMeta object at 0x7f866b7c24e0>
```

**Comment by danfike** [comment]
I think this might be our culprit here:
https://github.com/ibm-cds-labs/pixiedust/blob/master/pixiedust/display/display.py#L297-L301

I just attempted to download some data as JSON and got the same behavior. I can see in the browser console log a message like this:
```
running download command: display(bgg,cell_id='5E7F5543B10D46DEB9CDF0F3F9A069AE',nostore_pixiedust='true',kind='kde',kde='false',rowCount='2000',rug='true',chartsize='100',keyFields='Categories',binsize='34',handlerId='downloadFile',mpld3='false',valueFields='Rank',rendererId='seaborn',aggregation='COUNT',title='Ratin',nostore_cw='1098',org_params='nostore_pixiedust',prefix='b98d89af',doDownload='json',doDownloadCount=100,doDownloadLink='True')
```
If I throw that into a new cell in my notebook and run it, I can get a real callstack:
```
Traceback (most recent call last)
<ipython-input-6-817a1d6f6e8f> in <module>()
----> 1 display(bgg,cell_id='5E7F5543B10D46DEB9CDF0F3F9A069AE',nostore_pixiedust='true',kind='kde',kde='false',rowCount='2000',rug='true',chartsize='100',keyFields='Categories',binsize='34',handlerId='downloadFile',mpld3='false',valueFields='Rank',rendererId='seaborn',aggregation='COUNT',title='Ratin',nostore_cw='1098',org_params='nostore_pixiedust',prefix='b98d89af',doDownload='json',doDownloadCount=100,doDownloadLink='True')

.../python3.5/site-packages/pixiedust/display/__init__.py in display(entity, **kwargs)
    134                 return
    135 
--> 136             displayHandler.render()
    137         finally:
    138             if pr is not None:

.../python3.5/site-packages/pixiedust/display/display.py in render(self)
    264         else:
    265             start = time.clock()
--> 266             self.doRender(handlerId)
    267             self.executionTime = time.clock() - start
    268 

.../python3.5/site-packages/pixiedust/display/download/downloadFile.py in doRender(self, handlerId)
    103             for count, row in enumerate(entity.take(doDownloadCount), start=1):
    104                 print(" {")
--> 105                 print(reduce(lambda s,f: s+(",\n  " if s!="" else "  ")+"\""+self._safeString(f.name)+"\":"+(str(row[f.name]) if isinstance(row[f.name],(int,long, float)) else self._safeString("\""+("" if row[f.name] is None else row[f.name])+"\"")), schema.fields, ""))
    106                 print(" }," if count != doDownloadCount else " }")
    107             print("]")

.../python3.5/site-packages/pixiedust/display/download/downloadFile.py in <lambda>(s, f)
    103             for count, row in enumerate(entity.take(doDownloadCount), start=1):
    104                 print(" {")
--> 105                 print(reduce(lambda s,f: s+(",\n  " if s!="" else "  ")+"\""+self._safeString(f.name)+"\":"+(str(row[f.name]) if isinstance(row[f.name],(int,long, float)) else self._safeString("\""+("" if row[f.name] is None else row[f.name])+"\"")), schema.fields, ""))
    106                 print(" }," if count != doDownloadCount else " }")
    107             print("]")

TypeError: Can't convert 'bytes' object to str implicitly
```
Pretty sure this is because the `_safeString` function is returning `bytes` when you feed it a `str`, and then we try to do `str + bytes`.
```
Python 3.5.3 (default, Feb 16 2017, 23:43:43)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from functools import reduce
>>>
>>> def _safeString(s):
...     if not isinstance(s, str):
...         return str(s)
...     else:
...         return s.encode('ascii', 'ignore')
...
>>> objList = [8]
>>> reduce(lambda s,f: s + _safeString(f), objList, '')
'8'
>>>
>>> objList = ['foo']
>>> reduce(lambda s,f: s + _safeString(f), objList, '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
TypeError: Can't convert 'bytes' object to str implicitly
>>>
>>> 'foo'.encode('ascii', 'ignore')
b'foo'
>>> '' + b'foo'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't convert 'bytes' object to str implicitly
```

Note that this works fine in older versions of Python:
```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from functools import reduce
>>>
>>> def _safeString(s):
...     if not isinstance(s, str):
...         return str(s)
...     else:
...         return s.encode('ascii', 'ignore')
...
>>> objList = [8]
>>> reduce(lambda s,f: s + _safeString(f), objList, '')
'8'
>>>
>>> objList = ['foo']
>>> reduce(lambda s,f: s + _safeString(f), objList, '')
'foo'
>>>
>>> 'foo'.encode('ascii', 'ignore')
'foo'
```

**Comment by vabarbosa** [comment]
@danfike thanks. 
PR #712 has been submitted for review and merge.
it should resolve this issue and a couple others related to the file download.
