### ISSUE TITLE
As a developer, I want to install pixiedust without cloudant so that I can use pixiedust without thinking about cloudant

### ISSUE THREAD

**Issue by kheuton** [ibm-cds-labs/pixiedust#356]
### Expected behavior
I'm not sure what cloudant even is, I'd like to be able to use pixiedust without thinking about it

### Actual behavior
I was trying to install pixiedust today, and got this warning during the setup:
`Error downloading Cloudant Jar: [Errno 2] No such file or directory: 'PIXIEDUST_HOME/bin/cloudant-spark-v2.0.0-185.jar'. Install will continue without the spark Cloudant connector`

However, when I proceeded with the install, this occured:
```
Traceback (most recent call last):
  File "CONDA_ENV/bin/jupyter-pixiedust", line 11, in <module>
    load_entry_point('pixiedust', 'console_scripts', 'jupyter-pixiedust')()
  File "/share/forecasting/working/krheuton/pixiedust/install/pixiedustapp.py", line 42, in main
    PixiedustJupyterApp.launch_instance()
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-2>", line 2, in initialize
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "CONDA_ENV/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "CONDA_ENV/lib/python2.7/site-packages/jupyter_core/application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "PIXIEDUST_HOME/install/createKernel.py", line 240, in parse_command_line
    dest = self.createKernelSpec()
  File "PIXIEDUST_HOME/install/createKernel.py", line 473, in createKernelSpec
    self.sparkCloudantPath,
AttributeError: 'PixiedustInstall' object has no attribute 'sparkCloudantPath'
```

### Steps to reproduce the behavior

1. Install pixiedust from the source, using the latest master branch without having cloudant around
2. Attempt to install the kernel with `jupyter pixiedust install`

**Comment by kheuton** [comment]
I can't even replicate this now, I guess it was a fluke in the download process
